### ISSUE TITLE
Configure maven publishing

### ISSUE THREAD

**Issue by phelps-sg** [phelps-sg/play-hmac-signatures#2]

**Comment by felipebonezi** [comment]
@phelps-sg why don't we use `sbt-ci-release` plugin?
It's very easy to publish into Sonatype.

https://github.com/sbt/sbt-ci-release

**Comment by phelps-sg** [comment]
> @phelps-sg why don't we use `sbt-ci-release` plugin? It's very easy to publish into Sonatype.
> 
> https://github.com/sbt/sbt-ci-release

Sounds like a great idea.  Do you have any time to implement it?  If so greatly appreciated.

**Comment by felipebonezi** [comment]
Yeah, @phelps-sg 
But I would need you to configure some secrets to the project.
I already have other open-source projects that use and publish smoothly with this plugin.

**Comment by phelps-sg** [comment]
>But I would need you to configure some secrets to the project.

Happy to do this.  Let me know what you need.  I am also happy for you to change the organizational unit and/or use fresh signing keys if that's easier.

**Comment by felipebonezi** [comment]
> 

What is "change organizational unit"?
Could you explain to me?

**Comment by phelps-sg** [comment]
>What is "change organizational unit"?
Sorry I meant the group ID (currently `com.mesonomics`).

**Comment by phelps-sg** [comment]
Hi @felipebonezi I am not sure the sbt-ci-release plugin is working correctly.  Should it automatically deploy a SNAPSHOT on every commit to main branch?  If so, where should I work look for the output in the CI actions?

**Comment by felipebonezi** [comment]
> Hi @felipebonezi I am not sure the sbt-ci-release plugin is working correctly. Should it automatically deploy a SNAPSHOT on every commit to main branch? If so, where should I work look for the output in the CI actions?

No, it will publish every new release.
Did you created a new release?

**Comment by phelps-sg** [comment]
@felipebonezi  Yes it has deployed to Maven now that I have created a release.
Many thanks for all the help!
